#!perl

=head1 NAME

  SpeedTest

=cut

use strict;
use warnings;
use Time::Piece;
use Abills::Base qw(time2sec);
use SpeedTest::db::SpeedTest;
use Data::Dumper;
use Net::Address::IP::Local;
use CGI qw(:standard);

our ($html, %FORM, $db, %conf, $admin, %lang, $index);


#**********************************************************

=head2 open_st() - SpeedTest

=cut

#**********************************************************
sub open_st {
  # Get the local system IP address that is "en route" to "the internet":
  my $address = Net::Address::IP::Local->public;
  print $address;

  $html->tpl_show(_include('main_temp','SpeedTest'),{
    YOUR_IP => $address,
  });
  return 1;
}

1;

